// design/domain の公開 facade — 明示列挙のみ（export * 禁止）。

export { type DesignValue } from "./design-value.ts";
export { DesignTransition } from "./design-transition.ts";
export { DesignTransitionId } from "./design-transition-id.ts";
export { DesignTransitions } from "./design-transitions.ts";
export { DesignMachine } from "./design-machine.ts";
export { DesignAttributeName } from "./design-attribute-name.ts";
export { DesignEntityName } from "./design-entity-name.ts";
export { DesignIgnore } from "./design-ignore.ts";
export { DesignIgnores } from "./design-ignores.ts";
export { DesignMachineId } from "./design-machine-id.ts";
export { DesignMachines } from "./design-machines.ts";
export { DesignObligation } from "./design-obligation.ts";
export { DesignObligationId } from "./design-obligation-id.ts";
export { DesignObligationNature } from "./design-obligation-nature.ts";
export { DesignObligationOrigin } from "./design-obligation-origin.ts";
export { DesignObligations } from "./design-obligations.ts";
export { DesignScenario } from "./design-scenario.ts";
export { DesignScenarioId } from "./design-scenario-id.ts";
export { DesignScenarios } from "./design-scenarios.ts";
export { DesignUnit } from "./design-unit.ts";
export { AttrPaths } from "./attr-paths.ts";
export { type DesignBackgroundAssumption } from "./design-background-assumption.ts";
export { DesignBackgroundAssumptions } from "./design-background-assumptions.ts";
export { DesignBackgroundId } from "./design-background-id.ts";
export { DesignUnits } from "./design-units.ts";
export { DesignModel } from "./design-model.ts";
export { type DesignModelComposition } from "./design-model-composition.ts";
export { DesignFinding } from "./design-finding.ts";
export { DesignFindings } from "./design-findings.ts";
export { type DesignSkipped } from "./design-skipped.ts";
export { DesignSkips } from "./design-skips.ts";
export { ExpressionCanonicalKey } from "./expression-canonical-key.ts";
export { type LoweredBackground } from "./lowered-background.ts";
export { LoweredBackgrounds } from "./lowered-backgrounds.ts";
export { LoweredId } from "./lowered-id.ts";
export { type LoweredObligation } from "./lowered-obligation.ts";
export { LoweredObligations } from "./lowered-obligations.ts";
export { LoweredOriginRef } from "./lowered-origin-ref.ts";
export { type LoweredOrigin } from "./lowered-origin.ts";
export { type LoweredScenario } from "./lowered-scenario.ts";
export { LoweredScenarios } from "./lowered-scenarios.ts";
export { LoweredUnit } from "./lowered-unit.ts";
export { LoweringIndex } from "./lowering-index.ts";
export { type LoweringKind } from "./lowering-kind.ts";
export { type RemappedUnit } from "./remapped-unit.ts";
export { type SiblingVerdictDocument } from "./sibling-verdict-document.ts";
export { type SiblingVerdictFinding } from "./sibling-verdict-finding.ts";
export { SiblingVerdictFindings } from "./sibling-verdict-findings.ts";
export { type SiblingVerdictSkip } from "./sibling-verdict-skip.ts";
export { SiblingVerdictSkips } from "./sibling-verdict-skips.ts";
export { DesignReportId } from "./design-report-id.ts";
export { SUPPORTED_DESIGN_IR_MAJOR, DesignReport } from "./design-report.ts";
export { CheckedUnits } from "./checked-units.ts";
export { DesignCrossCheckedEntries } from "./design-cross-checked-entries.ts";
export { type DesignCrossCheckedEntry } from "./design-cross-checked-entry.ts";
export { type DesignInputAnchor } from "./design-input-anchor.ts";
export { DesignInputAnchors } from "./design-input-anchors.ts";
export { type DesignReportComposition } from "./design-report-composition.ts";
export { DesignReports } from "./design-reports.ts";
export { BindingPairs } from "./binding-pairs.ts";
export { BrRefs } from "./br-refs.ts";
export { DeclaredValues } from "./declared-values.ts";
export { DesignAttributeDecl } from "./design-attribute-decl.ts";
export { DesignAttributeDecls } from "./design-attribute-decls.ts";
export { DesignBackgroundDecl } from "./design-background-decl.ts";
export { DesignBackgroundDecls } from "./design-background-decls.ts";
export { DesignEntityDecl } from "./design-entity-decl.ts";
export { DesignEntityDecls } from "./design-entity-decls.ts";
export { DesignIgnoreDecl } from "./design-ignore-decl.ts";
export { DesignIgnoreDecls } from "./design-ignore-decls.ts";
export { DesignMachineDecl } from "./design-machine-decl.ts";
export { DesignMachineDecls } from "./design-machine-decls.ts";
export { DesignObligationDecl } from "./design-obligation-decl.ts";
export { DesignObligationDecls } from "./design-obligation-decls.ts";
export { DesignScenarioDecl } from "./design-scenario-decl.ts";
export { DesignScenarioDecls } from "./design-scenario-decls.ts";
export { DesignTransitionDecl } from "./design-transition-decl.ts";
export { DesignTransitionDecls } from "./design-transition-decls.ts";
export { DesignUnitDecl } from "./design-unit-decl.ts";
export { DesignUnitDecls } from "./design-unit-decls.ts";
export { InitialStates } from "./initial-states.ts";
export { UnformalizedTargets } from "./unformalized-targets.ts";
export { BrReferenceIndex } from "./br-reference-index.ts";
export { designWellFormednessErrors } from "./design-well-formedness.ts";
export { DesignModelId } from "./design-model-id.ts";
export { DesignUnitId } from "./design-unit-id.ts";
export { RefinementMaterialsId } from "./refinement-materials-id.ts";
export { DesignIrValidationMaterials } from "./design-ir-validation-materials.ts";
export { DesignIrValidationMaterialsId } from "./design-ir-validation-materials-id.ts";
