import type {
  Check,
  DesignArtifactReference,
  DesignArtifacts,
  HealthVerdict,
  InstallationManifest,
  ManifestEntry,
  PluginVersion,
  StableReleases,
  StageScope,
  StageScopes,
  StructuralDebt,
  StructuralObservation,
} from "@deep-spec-analysis/doctor-domain";
import type {
  Equatable,
  FirstClassCollection,
  NonEmptyFirstClassCollection,
  UnitName,
} from "@deep-spec-analysis/kernel-domain";
import type {
  AllowedValue,
  AllowedValues,
  AttributeDeclaration,
  AttributeDeclarations,
  AttributeName,
  AttributeNames,
  CheckFamilies,
  CheckFamily,
  Component,
  ComponentEntities,
  ComponentEntity,
  ComponentReference,
  ComponentReferences,
  ComponentShapeError,
  ComponentShapeErrors,
  Components,
  ContractRow,
  ContractRows,
  DomainEntitySketch,
  DomainEntitySketches,
  EntityDeclaration,
  EntityDeclarations,
  EntityReference,
  EntityReferences,
  Finding,
  Findings,
  InputAnchor,
  InputAnchors,
  RelationshipDeclaration,
  RelationshipDeclarations,
  RuleDeclaration,
  RuleDeclarations,
  ShapeError,
  ShapeErrors,
  SiblingUnitIndex,
  SiblingUnitIndexEntry,
  Skipped,
  Skips,
  SourceIdentifier,
  SourceIdentifiers,
  SpecificationBlockAssessment,
  SpecificationBlockAssessments,
  StateMachineSketch,
  StateMachineSketches,
  StateName,
  StateNames,
  UnitDeclaration,
  UnitDeclarations,
  UnitNames,
  WitnessReference,
  WitnessReferences,
} from "@deep-spec-analysis/refcheck-domain";
import type {
  BackgroundAssumption,
  BackgroundAssumptions,
  CrossCheckedEntries,
  CrossCheckedEntry,
  FunctionalRequirementReferenceClaim,
  FunctionalRequirementReferenceClaims,
  FunctionalRequirementReferenceIndex,
  IntermediateRepresentationAttributeCatalog,
  IntermediateRepresentationAttributeDeclaration,
  IntermediateRepresentationAttributeDeclarations,
  IntermediateRepresentationBackgroundDeclaration,
  IntermediateRepresentationBackgroundDeclarations,
  IntermediateRepresentationEntityDeclaration,
  IntermediateRepresentationEntityDeclarations,
  IntermediateRepresentationObligationDeclaration,
  IntermediateRepresentationObligationDeclarations,
  IntermediateRepresentationScenarioDeclaration,
  IntermediateRepresentationScenarioDeclarations,
  Obligation,
  ObligationIdentifier,
  ObligationIdentifiers,
  Obligations,
  QuintMachineComponent,
  QuintMachineComponents,
  RequirementAttributeDeclaration,
  RequirementAttributeDeclarations,
  SatisfiabilityModuloTheoriesEventPairProbe,
  SatisfiabilityModuloTheoriesEventPairProbes,
  SatisfiabilityModuloTheoriesQueryVerdictEntry,
  SatisfiabilityModuloTheoriesQueryVerdicts,
  Scenario,
  Scenarios,
  TraceState,
  TraceStateEntry,
  TraceStates,
  VerificationFinding,
  VerificationFindings,
  VerificationReport,
  VerificationReports,
  VerificationSkipped,
  VerificationSkips,
} from "@deep-spec-analysis/requirements-domain";

type Assert<T extends true> = T;
type Normal<C, E extends Equatable<E>> =
  C extends FirstClassCollection<E>
    ? ReturnType<C["tail"]> extends C
      ? ReturnType<C["filter"]> extends C
        ? true
        : false
      : false
    : false;
type NonEmpty<C, E extends Equatable<E>> = C extends NonEmptyFirstClassCollection<E> ? true : false;

type NormalCollections = [
  Normal<AllowedValues, AllowedValue>,
  Normal<AttributeDeclarations, AttributeDeclaration>,
  Normal<AttributeNames, AttributeName>,
  Normal<CheckFamilies, CheckFamily>,
  Normal<ComponentEntities, ComponentEntity>,
  Normal<ComponentReferences, ComponentReference>,
  Normal<ComponentShapeErrors, ComponentShapeError>,
  Normal<Components, Component>,
  Normal<ContractRows, ContractRow>,
  Normal<DomainEntitySketches, DomainEntitySketch>,
  Normal<EntityDeclarations, EntityDeclaration>,
  Normal<EntityReferences, EntityReference>,
  Normal<Findings, Finding>,
  Normal<InputAnchors, InputAnchor>,
  Normal<RelationshipDeclarations, RelationshipDeclaration>,
  Normal<RuleDeclarations, RuleDeclaration>,
  Normal<ShapeErrors, ShapeError>,
  Normal<Skips, Skipped>,
  Normal<SourceIdentifiers, SourceIdentifier>,
  Normal<SpecificationBlockAssessments, SpecificationBlockAssessment>,
  Normal<StateMachineSketches, StateMachineSketch>,
  Normal<StateNames, StateName>,
  Normal<UnitDeclarations, UnitDeclaration>,
  Normal<UnitNames, UnitName>,
  Normal<WitnessReferences, WitnessReference>,
  Normal<SiblingUnitIndex, SiblingUnitIndexEntry>,
  Normal<BackgroundAssumptions, BackgroundAssumption>,
  Normal<CrossCheckedEntries, CrossCheckedEntry>,
  Normal<FunctionalRequirementReferenceClaims, FunctionalRequirementReferenceClaim>,
  Normal<FunctionalRequirementReferenceIndex, FunctionalRequirementReferenceClaim>,
  Normal<FunctionalRequirementReferenceClaims, FunctionalRequirementReferenceClaim>,
  Normal<
    IntermediateRepresentationAttributeCatalog,
    import("@deep-spec-analysis/requirements-domain").IntermediateRepresentationAttributeEntry
  >,
  Normal<IntermediateRepresentationAttributeDeclarations, IntermediateRepresentationAttributeDeclaration>,
  Normal<IntermediateRepresentationBackgroundDeclarations, IntermediateRepresentationBackgroundDeclaration>,
  Normal<IntermediateRepresentationEntityDeclarations, IntermediateRepresentationEntityDeclaration>,
  Normal<IntermediateRepresentationObligationDeclarations, IntermediateRepresentationObligationDeclaration>,
  Normal<IntermediateRepresentationScenarioDeclarations, IntermediateRepresentationScenarioDeclaration>,
  Normal<ObligationIdentifiers, ObligationIdentifier>,
  Normal<Obligations, Obligation>,
  Normal<QuintMachineComponents, QuintMachineComponent>,
  Normal<RequirementAttributeDeclarations, RequirementAttributeDeclaration>,
  Normal<SatisfiabilityModuloTheoriesEventPairProbes, SatisfiabilityModuloTheoriesEventPairProbe>,
  Normal<SatisfiabilityModuloTheoriesQueryVerdicts, SatisfiabilityModuloTheoriesQueryVerdictEntry>,
  Normal<Scenarios, Scenario>,
  Normal<TraceState, TraceStateEntry>,
  Normal<TraceStates, TraceState>,
  Normal<VerificationFindings, VerificationFinding>,
  Normal<VerificationReports, VerificationReport>,
  Normal<VerificationSkips, VerificationSkipped>,
  Normal<DesignArtifacts, DesignArtifactReference>,
  Normal<HealthVerdict, Check>,
  Normal<StableReleases, PluginVersion>,
  Normal<StageScopes, StageScope>,
  Normal<StructuralDebt, StructuralObservation>,
][number];

export type EveryNormalCollectionUsesTheCommonOperations = Assert<NormalCollections extends true ? true : false>;

export type InstallationManifestKeepsItsNonEmptyContract = Assert<NonEmpty<InstallationManifest, ManifestEntry>>;

export type NonEmptyCollectionsDoNotExposeIsEmpty = Assert<"isEmpty" extends keyof InstallationManifest ? false : true>;
